config/routes.rb
Rails.application.routes.draw do

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 devise_for :users

  get "homes/top"
  get "home/about"=>"homes#about"
  root to:'homes#top'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites,only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
   resource :relationships,only: [:create, :destroy]
   get "relationships/following"
   get "relationships/follower"

  end
  get 'searches/search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book=Book.find(params[:book_id])
    @favorite=current_user.favorites.new(book_id: @book.id)
    @favorite.save
  end

  def destroy
    @book=Book.find(params[:book_id])
    @favorite=current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>

    <%= link_to book_favorites_path(book.id),method: :delete, remote: true do %>
      <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i><%= book.favorites.count %>
    <% end %>


<% else %>

    <%= link_to book_favorites_path(book.id), method: :post, remote: true do %>
       <i class="fas fa-heart" aria-hidden="true"></i><%= book.favorites.count %>
    <% end %>

<% end %>

app/views/favorites/create.js.erb
$('#favorite_button_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_button_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");