config/routes.rb
Rails.application.routes.draw do

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 devise_for :users

  get "homes/top"
  get "home/about"=>"homes#about"
  root to:'homes#top'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites,only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
   resource :relationships,only: [:create, :destroy]
   get "relationships/following"
   get "relationships/follower"

  end
  get 'searches/search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to:user
  belongs_to:book
  
  validates:comment,presence:true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book=Book.find(params[:book_id])
    @user=@book.user
    @comment=BookComment.new
    comment=current_user.book_comments.new(comment_params)
    comment.book_id=@book.id
    comment.save
    @comments=@book.book_comments
    render 'book_comments/post_comments'
  end

  def destroy
    @book=Book.find(params[:book_id])
    @user=@book.user
    @comment=BookComment.new
    @comments=@book.book_comments
    BookComment.find(params[:id]).destroy
    render 'book_comments/post_comments'
  end

private

def comment_params
  params.require(:book_comment).permit(:comment)
end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment1.html.erb
　　　　
        		  <tr>
          <td><%= link_to(book.user) do %>
            <%= image_tag book.user.get_profile_image, size:"100x100" %><br>
            <%= book.user.name %>
            <% end %>
          </td>
          <td><%= link_to book.title, book %></td>
          <td><%= book.body %></td>

          <td id="favorite_button_<%= book.id %>">
          　<%= render 'favorites/favorite', book: book %>
        　</td>

            <td>コメント数:<%= book.book_comments.count %></td>
           <% if book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(book), class: "btn btn-sm btn-success edit_book_#{book.id}" %></td>
            <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{book.id}"%></td>
           <% end %>
        </tr>
　　　　<% comments.each do |c| %>
        <tr>
          <td><%= image_tag user.get_profile_image,size:"100x100" %><br>
              <%= user.name %>
          </td>
          <td><%= c.comment %></td>
          <td><%= link_to "Destroy", book_book_comment_path(c.book_id,c.id), method: :delete, class: "btn btn-sm btn-danger", remote: true %></td>
        </tr>
　　　　 <% end %>

app/views/book_comments/_comment2.html.erb
        <%= form_with(model:[book, comment], local: false) do |f| %>
           <div class = "form-group">
              <%= f.text_area :comment, class:"form-control" %><br>
              <%= f.submit "送信" %>
           </div>
        <% end %>

app/views/book_comments/post_comments.js.erb
<!--id="comments_areaにrenderで指定した部分テンプレートに更新-->
$("#comments_area").html("<%= j(render 'book_comments/comment1', comments: @comments, user: @user, book: @book) %>");

<!--フォームを送信したあとにフォームの値を空にします-->
$("textarea").val('');